# This workflow triggers an azure policy compliance scan on multiple subscriptions, resource groups and resources
# The compliance scan action will progress successfully to the next step without waiting.
name: scan-subscriptions-no-wait
on: push

jobs:
  assess-policy-compliance:    
    runs-on: ubuntu-latest
    steps:
    # Azure Login       
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}} 
    
    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/a2e3e6cc-8780-48ab-a5ff-f6c91d53ef12/resourceGroups/rg-optumpay-poc
        wait: false
